services:
    db:
        image: postgres:16
        container_name: dentsis-db
        command: postgres -c 'max_connections=250'
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=P@ssw0rd
            - POSTGRES_DB=dentsis
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        restart: always
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -d dentsis -U admin"]
            interval: 10s
            timeout: 5s
            retries: 5

    # api:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     container_name: dentsis-api
    #     environment:
    #         - NODE_ENV=production
    #         - PORT=3000
    #         - DATABASE_URL=postgresql://admin:P@ssw0rd@db:5432/dentsis
    #     ports:
    #         - "3000:3000"
    #     depends_on:
    #         db:
    #             condition: service_healthy
    #     restart: always
