services:
    db:
        image: postgres:16
        container_name: dentsis-db
        command: postgres -c 'max_connections=250'
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=P@ssw0rd
            - POSTGRES_DB=dentsis
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        restart: always
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -d dentsis -U admin"]
            interval: 10s
            timeout: 5s
            retries: 5
